-- Seed products (prices the server trusts). Re-run after changing prices.
insert into products (id, name, price, stock, active) values
  ('01_starry_sky_moon_lamp', 'Starry Sky Moon Lamp', 1299, 100, true),
  ('11_magnetic_pocket_phone_stand', 'Magnetic Pocket Phone Stand', 499, 100, true),
  ('12_typec_docking_station_stand', 'Type-C Docking Station Stand', 1499, 100, true),
  ('13_wooden_coaster_set', 'Wooden Coaster Set', 399, 100, true),
  ('14_gift_pack_cable_storage_box', 'Gift Pack Cable Storage Box', 599, 100, true),
  ('17_glue_handbag_phone_case', 'Handbag Phone Case', 699, 100, true),
  ('18_diamond_gemstone_phone_case', 'Diamond Gemstone Phone Case', 799, 100, true),
  ('19_bluetooth_finger_robot', 'Bluetooth Finger Robot', 999, 100, true),
  ('20_magnetic_neck_fan', 'Magnetic Neck Fan', 899, 100, true),
  ('21_ai_face_tracking_selfie_stick', 'AI Face-Tracking Selfie Stick', 1499, 100, true),
  ('22_butterfly_phone_stand', 'Butterfly Phone Stand', 1000, 100, true),
  ('23_nail_art_steel_plates', 'Nail Art Steel Plates', 349, 100, true),
  ('240w_folding_stand_data_cable', '240W Folding Stand Cable', 399, 100, true),
  ('24_silicone_folding_water_bottle', 'Silicone Folding Water Bottle', 449, 100, true),
  ('25_keychain_shopping_tote', 'Keychain Shopping Tote', 299, 100, true),
  ('26_foldable_bluetooth_keyboard', 'Foldable Bluetooth Keyboard', 1799, 100, true),
  ('27_photography_fill_light_stand', 'Photography Fill Light Stand', 1299, 100, true),
  ('28_ai_face_tracking_phone_bracket', 'AI Face-Tracking Phone Bracket', 1399, 100, true),
  ('disposable_travel_compression_socks', 'Travel Compression Socks', 249, 100, true),
  ('flexible_deformable_device_stand', 'Flexible Deformable Device Stand', 899, 100, true),
  ('folding_nail_clippers_keychain', 'Folding Nail Clippers Keychain', 199, 100, true),
  ('large_capacity_travel_tote_bag', 'Large Capacity Travel Tote Bag', 999, 100, true),
  ('magnetic_multi_device_holder', 'Magnetic Multi-Device Holder', 799, 100, true),
  ('no_drill_telescopic_towel_rack', 'No-Drill Telescopic Towel Rack', 549, 100, true),
  ('portable_cable_storage_box', 'Portable Cable Storage Box', 449, 100, true),
  ('travel_duffel_bag_with_trolley_rod', 'Travel Duffel Bag with Trolley Rod', 1299, 100, true),
  ('wireless_remote_light_switch', 'Wireless Remote Light Switch', 1499, 100, true)
on conflict (id) do update set name=excluded.name, price=excluded.price, active=excluded.active;
