-- ═══════════════════════════════════════════════════════════════
--  THE AIM — FULL PRODUCT SEED  (self-contained)
--
--  STEP 1 adds the columns the products table needs.
--  STEP 2 loads every product with its images, descriptions,
--         category and video.
--
--  Safe to run as many times as you like. If a column already
--  exists it is skipped; existing products are updated, not
--  duplicated.
-- ═══════════════════════════════════════════════════════════════

-- ── STEP 1: make sure the columns exist ──
alter table products add column if not exists short_desc  text;
alter table products add column if not exists description text;
alter table products add column if not exists category    text;
alter table products add column if not exists mrp         numeric;
alter table products add column if not exists images      jsonb default '[]'::jsonb;
alter table products add column if not exists video       text;
alter table products add column if not exists status      text default 'active';
alter table products add column if not exists stock       int  default 100;
alter table products add column if not exists active      boolean default true;

-- ── STEP 2: load every product ──
insert into products
  (id, name, price, short_desc, description, category, stock, images, video, status, active)
values
  ('01_starry_sky_moon_lamp', 'Starry Sky Moon Lamp', 1299, '3D-printed moon lamp with starry-sky projection modes — touch control, USB rechargeable.', '3D-printed moon lamp with starry-sky projection modes — touch control, USB rechargeable.', 'Room', 100, '["images/products/01_starry_sky_moon_lamp_hero.webp", "images/products/01_starry_sky_moon_lamp_02.webp", "images/products/01_starry_sky_moon_lamp_05.webp", "images/products/01_starry_sky_moon_lamp_06.webp", "images/products/01_starry_sky_moon_lamp_07.webp", "images/products/01_starry_sky_moon_lamp_08.webp", "images/products/01_starry_sky_moon_lamp_09.webp", "images/products/01_starry_sky_moon_lamp_10.webp"]'::jsonb, null, 'active', true),
  ('11_magnetic_pocket_phone_stand', 'Magnetic Pocket Phone Stand', 499, 'Card-thin magnetic stand that lives in your pocket and props your phone anywhere.', 'Card-thin magnetic stand that lives in your pocket and props your phone anywhere.', 'Desk', 100, '["images/products/11_magnetic_pocket_phone_stand_hero.webp", "images/products/11_magnetic_pocket_phone_stand_01.webp", "images/products/11_magnetic_pocket_phone_stand_02.webp", "images/products/11_magnetic_pocket_phone_stand_03.webp"]'::jsonb, null, 'active', true),
  ('12_typec_docking_station_stand', 'Type-C Docking Station Stand', 1499, 'Phone stand with a built-in Type-C hub — charge and connect while you work.', 'Phone stand with a built-in Type-C hub — charge and connect while you work.', 'Desk', 100, '["images/products/12_typec_docking_station_stand_hero.webp", "images/products/12_typec_docking_station_stand_01.webp", "images/products/12_typec_docking_station_stand_02.webp", "images/products/12_typec_docking_station_stand_03.webp", "images/products/12_typec_docking_station_stand_04.webp"]'::jsonb, null, 'active', true),
  ('13_wooden_coaster_set', 'Wooden Coaster Set', 399, 'Solid wood coasters with a holder — keeps rings off your desk, looks good doing it.', 'Solid wood coasters with a holder — keeps rings off your desk, looks good doing it.', 'Desk', 100, '["images/products/13_wooden_coaster_set_hero.webp", "images/products/13_wooden_coaster_set_01.webp", "images/products/13_wooden_coaster_set_02.webp"]'::jsonb, null, 'active', true),
  ('14_gift_pack_cable_storage_box', 'Gift Pack Cable Storage Box', 599, 'Compartment box that untangles your cable drawer — gift-ready packaging.', 'Compartment box that untangles your cable drawer — gift-ready packaging.', 'Storage', 100, '["images/products/14_gift_pack_cable_storage_box_hero.webp", "images/products/14_gift_pack_cable_storage_box_01.webp", "images/products/14_gift_pack_cable_storage_box_02.webp", "images/products/14_gift_pack_cable_storage_box_03.webp", "images/products/14_gift_pack_cable_storage_box_04.webp", "images/products/14_gift_pack_cable_storage_box_05.webp"]'::jsonb, null, 'active', true),
  ('17_glue_handbag_phone_case', 'Handbag Phone Case', 699, 'Phone case with a handbag-style strap — carry hands-free, drop-protected.', 'Phone case with a handbag-style strap — carry hands-free, drop-protected.', 'Gadgets', 100, '["images/products/17_glue_handbag_phone_case_HERO.webp", "images/products/17_glue_handbag_phone_case_01.webp", "images/products/17_glue_handbag_phone_case_02.webp", "images/products/17_glue_handbag_phone_case_03.webp", "images/products/17_glue_handbag_phone_case_04.webp"]'::jsonb, null, 'active', true),
  ('18_diamond_gemstone_phone_case', 'Diamond Gemstone Phone Case', 799, 'Gemstone-studded case that turns your phone into jewellery.', 'Gemstone-studded case that turns your phone into jewellery.', 'Gadgets', 100, '["images/products/18_diamond_gemstone_phone_case_HERO.webp", "images/products/18_diamond_gemstone_phone_case_01.webp", "images/products/18_diamond_gemstone_phone_case_02.webp"]'::jsonb, null, 'active', true),
  ('19_bluetooth_finger_robot', 'Bluetooth Finger Robot', 999, 'Tiny Bluetooth robot that physically taps buttons and switches on command.', 'Tiny Bluetooth robot that physically taps buttons and switches on command.', 'Gadgets', 100, '["images/products/19_bluetooth_finger_robot_hero.webp", "images/products/19_bluetooth_finger_robot_01.webp", "images/products/19_bluetooth_finger_robot_02.webp"]'::jsonb, null, 'active', true),
  ('20_magnetic_neck_fan', 'Magnetic Neck Fan', 899, 'Hands-free neck fan with magnetic mount — bladeless airflow, USB rechargeable.', 'Hands-free neck fan with magnetic mount — bladeless airflow, USB rechargeable.', 'Gadgets', 100, '["images/products/20_magnetic_neck_fan_hero.webp", "images/products/20_magnetic_neck_fan_01.webp", "images/products/20_magnetic_neck_fan_02.webp"]'::jsonb, null, 'active', true),
  ('21_ai_face_tracking_selfie_stick', 'AI Face-Tracking Selfie Stick', 1499, 'Selfie stick that follows your face automatically — no cameraman needed.', 'Selfie stick that follows your face automatically — no cameraman needed.', 'Gadgets', 100, '["images/products/21_ai_face_tracking_selfie_stick_hero.webp", "images/products/21_ai_face_tracking_selfie_stick_01.webp", "images/products/21_ai_face_tracking_selfie_stick_02.webp", "images/products/21_ai_face_tracking_selfie_stick_03.webp"]'::jsonb, null, 'active', true),
  ('22_butterfly_phone_stand', 'Butterfly Phone Stand', 1000, 'Butterfly-shaped aluminum desktop stand that holds your phone or tablet at a 360°-adjustab', 'Butterfly-shaped aluminum desktop stand that holds your phone or tablet at a 360°-adjustable angle and folds flat when not in use. A decorative, sturdy stand for video calls, recipes, or hands-free viewing.', 'Desk', 100, '["images/products/22_butterfly_phone_stand_hero.webp", "images/products/22_butterfly_phone_stand_01.webp", "images/products/22_butterfly_phone_stand_02.webp", "images/products/22_butterfly_phone_stand_03.webp", "images/products/22_butterfly_phone_stand_04.webp"]'::jsonb, 'https://www.youtube.com/watch?v=ScMzIvxBSi4', 'active', true),
  ('23_nail_art_steel_plates', 'Nail Art Steel Plates', 349, 'Etched steel stamping plates for salon-grade nail art at home.', 'Etched steel stamping plates for salon-grade nail art at home.', 'Daily Essentials', 100, '["images/products/23_nail_art_steel_plates_hero.webp", "images/products/23_nail_art_steel_plates_01.webp", "images/products/23_nail_art_steel_plates_02.webp", "images/products/23_nail_art_steel_plates_03.webp", "images/products/23_nail_art_steel_plates_04.webp", "images/products/23_nail_art_steel_plates_05.webp"]'::jsonb, null, 'active', true),
  ('240w_folding_stand_data_cable', '240W Folding Stand Cable', 399, 'Fast-charge cable that folds into a phone stand — Type-C to Type-C, 240W.', 'Fast-charge cable that folds into a phone stand — Type-C to Type-C, 240W.', 'Desk', 100, '["images/products/240w_folding_stand_data_cable_hero.webp", "images/products/240w_folding_stand_data_cable_01.webp", "images/products/240w_folding_stand_data_cable_02.webp", "images/products/240w_folding_stand_data_cable_03.webp", "images/products/240w_folding_stand_data_cable_04.webp"]'::jsonb, null, 'active', true),
  ('24_silicone_folding_water_bottle', 'Silicone Folding Water Bottle', 449, 'Collapses to half its size when empty — leak-proof, food-grade silicone.', 'Collapses to half its size when empty — leak-proof, food-grade silicone.', 'Daily Essentials', 100, '["images/products/24_silicone_folding_water_bottle_hero.webp", "images/products/24_silicone_folding_water_bottle_01.webp", "images/products/24_silicone_folding_water_bottle_02.webp", "images/products/24_silicone_folding_water_bottle_03.webp", "images/products/24_silicone_folding_water_bottle_04.webp"]'::jsonb, null, 'active', true),
  ('25_keychain_shopping_tote', 'Keychain Shopping Tote', 299, 'Full-size tote that packs into a keychain pouch — always on you.', 'Full-size tote that packs into a keychain pouch — always on you.', 'Daily Essentials', 100, '["images/products/25_keychain_shopping_tote_hero.webp", "images/products/25_keychain_shopping_tote_01.webp", "images/products/25_keychain_shopping_tote_02.webp"]'::jsonb, null, 'active', true),
  ('26_foldable_bluetooth_keyboard', 'Foldable Bluetooth Keyboard', 1799, 'Full keyboard that folds to pocket size — pairs with phone, tablet, laptop.', 'Full keyboard that folds to pocket size — pairs with phone, tablet, laptop.', 'Desk', 100, '["images/products/26_foldable_bluetooth_keyboard_hero.webp", "images/products/26_foldable_bluetooth_keyboard_01.webp", "images/products/26_foldable_bluetooth_keyboard_02.webp", "images/products/26_foldable_bluetooth_keyboard_03.webp", "images/products/26_foldable_bluetooth_keyboard_04.webp"]'::jsonb, null, 'active', true),
  ('27_photography_fill_light_stand', 'Photography Fill Light Stand', 1299, 'Adjustable fill light on a stand — even lighting for calls and content.', 'Adjustable fill light on a stand — even lighting for calls and content.', 'Gadgets', 100, '["images/products/27_photography_fill_light_stand_hero.webp", "images/products/27_photography_fill_light_stand_01.webp", "images/products/27_photography_fill_light_stand_02.webp", "images/products/27_photography_fill_light_stand_03.webp"]'::jsonb, null, 'active', true),
  ('28_ai_face_tracking_phone_bracket', 'AI Face-Tracking Phone Bracket', 1399, 'Desk bracket that rotates to keep your face in frame automatically.', 'Desk bracket that rotates to keep your face in frame automatically.', 'Gadgets', 100, '["images/products/28_ai_face_tracking_phone_bracket_hero.webp", "images/products/28_ai_face_tracking_phone_bracket_01.webp", "images/products/28_ai_face_tracking_phone_bracket_02.webp", "images/products/28_ai_face_tracking_phone_bracket_03.webp"]'::jsonb, null, 'active', true),
  ('disposable_travel_compression_socks', 'Travel Compression Socks', 249, 'Disposable compression socks for long flights and train rides.', 'Disposable compression socks for long flights and train rides.', 'Daily Essentials', 100, '["images/products/disposable_travel_compression_socks_hero.webp", "images/products/disposable_travel_compression_socks_01.webp", "images/products/disposable_travel_compression_socks_03.webp", "images/products/disposable_travel_compression_socks_03.webp"]'::jsonb, null, 'active', true),
  ('flexible_deformable_device_stand', 'Flexible Deformable Device Stand', 899, 'Bendable stand that holds any device at any angle — reshapes in seconds.', 'Bendable stand that holds any device at any angle — reshapes in seconds.', 'Desk', 100, '["images/products/flexible_deformable_device_stand_hero.webp", "images/products/flexible_deformable_device_stand_01.webp", "images/products/flexible_deformable_device_stand_02.webp", "images/products/flexible_deformable_device_stand_03.webp", "images/products/flexible_deformable_device_stand_04.webp", "images/products/flexible_deformable_device_stand_05.webp", "images/products/flexible_deformable_device_stand_06.webp"]'::jsonb, null, 'active', true),
  ('folding_nail_clippers_keychain', 'Folding Nail Clippers Keychain', 199, 'Folding clippers that clip to your keys — sharp, compact, always there.', 'Folding clippers that clip to your keys — sharp, compact, always there.', 'Daily Essentials', 100, '["images/products/folding_nail_clippers_keychain_hero.webp", "images/products/folding_nail_clippers_keychain_01.webp", "images/products/folding_nail_clippers_keychain_02.webp", "images/products/folding_nail_clippers_keychain_03.webp", "images/products/folding_nail_clippers_keychain_04.webp"]'::jsonb, null, 'active', true),
  ('large_capacity_travel_tote_bag', 'Large Capacity Travel Tote Bag', 999, 'Oversized travel tote with structured compartments — carry-on friendly.', 'Oversized travel tote with structured compartments — carry-on friendly.', 'Storage', 100, '["images/products/large_capacity_travel_tote_bag_hero.webp", "images/products/large_capacity_travel_tote_bag_01.webp", "images/products/large_capacity_travel_tote_bag_02.webp", "images/products/large_capacity_travel_tote_bag_03.webp", "images/products/large_capacity_travel_tote_bag_04.webp"]'::jsonb, null, 'active', true),
  ('magnetic_multi_device_holder', 'Magnetic Multi-Device Holder', 799, 'Magnetic arms hold phone, tablet, and accessories in one folding stand.', 'Magnetic arms hold phone, tablet, and accessories in one folding stand.', 'Desk', 100, '["images/products/magnetic_multi_device_holder_hero.webp", "images/products/magnetic_multi_device_holder_01.webp", "images/products/magnetic_multi_device_holder_02.webp", "images/products/magnetic_multi_device_holder_03.webp", "images/products/magnetic_multi_device_holder_04.webp"]'::jsonb, null, 'active', true),
  ('no_drill_telescopic_towel_rack', 'No-Drill Telescopic Towel Rack', 549, 'Telescopic rack that mounts without drilling — strong hold on any wall.', 'Telescopic rack that mounts without drilling — strong hold on any wall.', 'Room', 100, '["images/products/no_drill_telescopic_towel_rack_hero.webp", "images/products/no_drill_telescopic_towel_rack_01.webp", "images/products/no_drill_telescopic_towel_rack_02_.webp", "images/products/no_drill_telescopic_towel_rack_03_.webp", "images/products/no_drill_telescopic_towel_rack_04.webp", "images/products/no_drill_telescopic_towel_rack_05.webp"]'::jsonb, null, 'active', true),
  ('portable_cable_storage_box', 'Portable Cable Storage Box', 449, 'Zip-shut box that keeps cables, adapters, and drives in one place.', 'Zip-shut box that keeps cables, adapters, and drives in one place.', 'Storage', 100, '["images/products/portable_cable_storage_box_hero.webp", "images/products/portable_cable_storage_box_01.webp", "images/products/portable_cable_storage_box_02.webp", "images/products/portable_cable_storage_box_03.webp", "images/products/portable_cable_storage_box_04.webp"]'::jsonb, null, 'active', true),
  ('travel_duffel_bag_with_trolley_rod', 'Travel Duffel Bag with Trolley Rod', 1299, 'Duffel with a built-in trolley sleeve — sits on your suitcase handle.', 'Duffel with a built-in trolley sleeve — sits on your suitcase handle.', 'Storage', 100, '["images/products/travel_duffel_bag_with_trolley_rod_hero.webp", "images/products/travel_duffel_bag_with_trolley_rod_01.webp", "images/products/travel_duffel_bag_with_trolley_rod_02.webp", "images/products/travel_duffel_bag_with_trolley_rod_03.webp", "images/products/travel_duffel_bag_with_trolley_rod_04.webp", "images/products/travel_duffel_bag_with_trolley_rod_05.webp", "images/products/travel_duffel_bag_with_trolley_rod_06.webp"]'::jsonb, null, 'active', true),
  ('wireless_remote_light_switch', 'Wireless Remote Light Switch', 1499, 'Control any light switch from your bed — sticks on, no wiring needed.', 'Control any light switch from your bed — sticks on, no wiring needed.', 'Room', 100, '["images/products/wireless_remote_light_switch_hero.webp", "images/products/wireless_remote_light_switch_01.webp", "images/products/wireless_remote_light_switch_02.webp", "images/products/wireless_remote_light_switch_03.webp"]'::jsonb, null, 'active', true)
on conflict (id) do update set
  name        = excluded.name,
  price       = excluded.price,
  short_desc  = excluded.short_desc,
  description = excluded.description,
  category    = excluded.category,
  images      = excluded.images,
  video       = excluded.video,
  status      = excluded.status,
  active      = excluded.active;
